Vagrant.configure("2") do |config|
    config.vm.box = "eurolinux-vagrant/centos-stream-9"
    config.vm.hostname = "tomcat-service"
    
    config.vm.network "private_network", ip: "192.168.56.11"
    config.vm.network "public_network"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
    end
end