Vagrant.configure("2") do |config|
  config.vm.box = "eurolinux-vagrant/centos-stream-9"
  config.vm.hostname = "eco-lume-iac"
  
  # IP
  config.vm.network "private_network", ip: "192.168.34.22"
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum install httpd wget unzip -y
    systemctl start httpd
    systemctl enable httpd
    mkdir -p /var/www/html
    mkdir -p /tmp/eco-lume-iac
    cd /tmp/eco-lume-iac
    wget https://www.tooplate.com/zip-templates/2145_eco_lume.zip
    unzip -o 2145_eco_lume.zip 
    cp -r 2145_eco_lume/* /var/www/html/
    systemctl restart httpd
    rm -rf /tmp/eco-lume-iac
  SHELL
end